name: Despliegue a Github Pages

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3
      - name: Configuramos entorno git en ubuntu para conexi贸n con Github
        run: |
         mkdir -p ~/.ssh/
         echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
         sudo chmod 600 ~/.ssh/id_rsa
      - name: Creamos la configuraci贸n de git para identificaci贸n
        run: |
          git config --global user.email "gh-pages@agh.local
          git config --global user.name "gh-pages"
      - name: Instalaci贸n dependencias de npm en maquina de despliegue (solo prod.)
        run: npm ci
      - name: Build
        run: npm run build
      - name: Despliegue
        run: npm run deploy -- -r git@github.com:AghLearning/LCXI_MVII_LAB_CLOUD_Front.git


